#----------------------------------------------------------------------
# GCTA power calculator - for genetic correlation
## between a behavioural trait/ brain measure
## given h2 estimates and N
#----------------------------------------------------------------------
library(tidyr)
#----------------------------------------------------------------------

#----------------------------------------------------------------------
options(stringsAsFactors = FALSE)
# define pattern for this run
root="ABCD_release_3.0_QCed_EUR.EUR6sd_unrelated.cleaned_rm05_adj"

# define working_dir
if (Sys.info()['sysname']=='Windows') {dir="F:/projects/"} else {dir="/export/home/acarrion/acarrion/projects/"}
working_dir=paste(dir,"resources/datasets/ABCD/data/working_data/genotyping/GCTA/",sep="")
out_dir=paste(working_dir,"/output/",sep="")


# Get functions from:
## https://gcta.freeforums.net/thread/164/gcta-greml-power-calculator
scripts_dir=paste0(dir,"/resources/datasets/ABCD/scripts/genetics/GCTA/")
source(paste0(scripts_dir,"GCTA_PowerCalculator.R"))

## Convert observed h2 to liability scale
## https://github.com/saralpulit/Afib-Stroke-Overlap/blob/master/h2.obs2liab.R
## prevalence =  estimated trait prevalence
## cases = total number of cases, controls = total number of controls
## h2obs = h2 on the observed scale
h2liab <- function(prevalence, cases, controls, h2obs) {
  
  P <- cases/(cases + controls)
  Z <- sqrt(2)*erfcinv(2*prevalence)
  f <- 1/sqrt(2*pi) * exp(-Z^2/2)
  obs_to_liab <- (prevalence*(1-prevalence))^2/(P*(1-P))/f^2
  h2.liab <- h2obs * obs_to_liab
  
  return(h2.liab)
  
}
# 

setwd(out_dir)
#----------------------------------------------------------------------
# read estimates from heritability analyses, min and max for phenotypes of interest
## generated by: hsq_results_parse.R
estimates_all<-read.csv(paste(out_dir,"gcta_estimates_h2_",root,".csv",sep=""),header=TRUE)
#
estimates_cogn<-estimates_all[grep("nihtbx",estimates_all$file),]
estimates_brain<-estimates_all[grep("nihtbx",estimates_all$file,invert=TRUE),]
#----------------------------------

#----------------------------------
# Define variables, h2 and rg - for all models
rgs=unique(c(seq(0.01,0.30,0.001),seq(0.31,0.49,0.01),seq(0.5,1,0.05))) #60
#----------------------------------
# Model Trait 2 from summary table
#----------------------------------
resultsQT <- data.frame(trait1=as.character(),trait2=as.character(),adj=as.character(),
                        N_1 = as.numeric(), N_2=as.numeric(),
                        h2_1 = as.numeric(), h2_2= as.numeric(), 
                        rg= as.numeric(), 
                        se = as.numeric(), ncp = as.numeric(), pwr = as.numeric())

# for each of the cognitive traits, run power analysis
for (j in 1:NROW(estimates_cogn)){
  h1<-estimates_cogn$h2[j]
  n1<-estimates_cogn$n[j]
  p1<-estimates_cogn$p1[j]
  for (i in 1:NROW(estimates_brain)){
  
  h2<-estimates_brain$h2[i]
  n2<-estimates_brain$n[i]
  p2<-estimates_brain$p1[i]
  adj<-estimates_brain$adj[i]
    if (!is.na(h2)){
      for (rg in rgs){
          tmp <- calcBiQt(n1=n1, n2=n2,hsq1 =h1,hsq2=h2,rg=rg,overlap=FALSE)
          resultsQT[nrow(resultsQT)+1,] <- c(list(trait1=p1,trait2=p2,adj=adj,N_1=n1,N_2=n2,hsq1=h1,hsq2=h2,rg=rg),tmp)
      }
    rm(rg,tmp,h2,n2,p2,adj)
    
  }
  rm(h2)
  }
}
resultsQT$rg<-as.numeric(resultsQT$rg)
resultsQT1<-merge(resultsQT,estimates_all[,c("p1","category","region","hemisphere")],by.x="trait2",by.y="p1")
resultsQT2<-merge(resultsQT1,estimates_all[,c("p1","category")],by.x="trait1",by.y="p1",all.x=TRUE,suffixes=c(".1",".2"))
#-----------------------
resultsQT2$trait2<- gsub("_adjGlobal","",resultsQT2$trait2)
# save files
write.csv(resultsQT2,paste(out_dir,"power_calc_results_",root,".csv",sep=""),row.names = FALSE)
